name: aas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: 1.4.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.0
  dio: ^5.0.0
  go_router: ^12.0.0
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#636363"
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: scaleAspectFill
  web: true
